In [19]:
from sklearn.datasets import load_wine
import pandas as pd
n = 10

# Load the dataset
wine = load_wine()

# Create a DataFrame
df = pd.DataFrame(wine.data, columns=wine.feature_names)

# Adding target variable
df['target'] = wine.target

df.head()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,0

In [20]:
df.head(n)

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,0
5,14.20,1.76,2.45,15.2,112.0,3.27,3.39,0.34,1.97,6.75,1.05,2.85,1450.0,0
6,14.39,1.87,2.45,14.6,96.0,2.50,2.52,0.30,1.98,5.25,1.02,3.58,1290.0,0
7,14.06,2.15,2.61,17.6,121.0,2.60,2.51,0.31,1.25,5.05,1.06,3.58,1295.0,0
8,14.83,1.64,2.17,14.0,97.0,2.80,2.98,0.29,1.98,5.20,1.08,2.85,1045.0,0
9,13.86,1.35,2.27,16.0,98.0,2.98,3.15,0.22,1.85,7.22,1.01,3.55,1045.0,0

In [21]:
df.tail(n)

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
168,13.58,2.58,2.69,24.5,105.0,1.55,0.84,0.39,1.54,8.660000,0.74,1.80,750.0,2
169,13.40,4.60,2.86,25.0,112.0,1.98,0.96,0.27,1.11,8.500000,0.67,1.92,630.0,2
170,12.20,3.03,2.32,19.0,96.0,1.25,0.49,0.40,0.73,5.500000,0.66,1.83,510.0,2
171,12.77,2.39,2.28,19.5,86.0,1.39,0.51,0.48,0.64,9.899999,0.57,1.63,470.0,2
172,14.16,2.51,2.48,20.0,91.0,1.68,0.70,0.44,1.24,9.700000,0.62,1.71,660.0,2
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.700000,0.64,1.74,740.0,2
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.300000,0.70,1.56,750.0,2
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.200000,0.59,1.56,835.0,2
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.300000,0.60,1.62,840.0,2
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.200000,0.61,1.60,560.0,2

In [22]:
df.sample(n)

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
95,12.47,1.52,2.20,19.0,162.0,2.50,2.27,0.32,3.28,2.60,1.16,2.63,937.0,1
27,13.30,1.72,2.14,17.0,94.0,2.40,2.19,0.27,1.35,3.95,1.02,2.77,1285.0,0
115,11.03,1.51,2.20,21.5,85.0,2.46,2.17,0.52,2.01,1.90,1.71,2.87,407.0,1
49,13.94,1.73,2.27,17.4,108.0,2.88,3.54,0.32,2.08,8.90,1.12,3.10,1260.0,0
41,13.41,3.84,2.12,18.8,90.0,2.45,2.68,0.27,1.48,4.28,0.91,3.00,1035.0,0
159,13.48,1.67,2.64,22.5,89.0,2.60,1.10,0.52,2.29,11.75,0.57,1.78,620.0,2
77,11.84,2.89,2.23,18.0,112.0,1.72,1.32,0.43,0.95,2.65,0.96,2.52,500.0,1
166,13.45,3.70,2.60,23.0,111.0,1.70,0.92,0.43,1.46,10.68,0.85,1.56,695.0,2
71,13.86,1.51,2.67,25.0,86.0,2.95,2.86,0.21,1.87,3.38,1.36,3.16,410.0,1
134,12.51,1.24,2.25,17.5,85.0,2.00,0.58,0.60,1.25,5.45,0.75,1.51,650.0,2

In [23]:
df.iloc[:n]

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,0
1,13.20,1.78,2.14,11.2,100.0,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050.0,0
2,13.16,2.36,2.67,18.6,101.0,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185.0,0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,0
4,13.24,2.59,2.87,21.0,118.0,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735.0,0
5,14.20,1.76,2.45,15.2,112.0,3.27,3.39,0.34,1.97,6.75,1.05,2.85,1450.0,0
6,14.39,1.87,2.45,14.6,96.0,2.50,2.52,0.30,1.98,5.25,1.02,3.58,1290.0,0
7,14.06,2.15,2.61,17.6,121.0,2.60,2.51,0.31,1.25,5.05,1.06,3.58,1295.0,0
8,14.83,1.64,2.17,14.0,97.0,2.80,2.98,0.29,1.98,5.20,1.08,2.85,1045.0,0
9,13.86,1.35,2.27,16.0,98.0,2.98,3.15,0.22,1.85,7.22,1.01,3.55,1045.0,0

In [24]:
df.iloc[-n:]

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
168,13.58,2.58,2.69,24.5,105.0,1.55,0.84,0.39,1.54,8.660000,0.74,1.80,750.0,2
169,13.40,4.60,2.86,25.0,112.0,1.98,0.96,0.27,1.11,8.500000,0.67,1.92,630.0,2
170,12.20,3.03,2.32,19.0,96.0,1.25,0.49,0.40,0.73,5.500000,0.66,1.83,510.0,2
171,12.77,2.39,2.28,19.5,86.0,1.39,0.51,0.48,0.64,9.899999,0.57,1.63,470.0,2
172,14.16,2.51,2.48,20.0,91.0,1.68,0.70,0.44,1.24,9.700000,0.62,1.71,660.0,2
173,13.71,5.65,2.45,20.5,95.0,1.68,0.61,0.52,1.06,7.700000,0.64,1.74,740.0,2
174,13.40,3.91,2.48,23.0,102.0,1.80,0.75,0.43,1.41,7.300000,0.70,1.56,750.0,2
175,13.27,4.28,2.26,20.0,120.0,1.59,0.69,0.43,1.35,10.200000,0.59,1.56,835.0,2
176,13.17,2.59,2.37,20.0,120.0,1.65,0.68,0.53,1.46,9.300000,0.60,1.62,840.0,2
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.200000,0.61,1.60,560.0,2

In [25]:
mask = df['alcohol'] > 14
df.loc[mask]

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
0,14.23,1.71,2.43,15.6,127.0,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065.0,0
3,14.37,1.95,2.50,16.8,113.0,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480.0,0
5,14.20,1.76,2.45,15.2,112.0,3.27,3.39,0.34,1.97,6.75,1.05,2.85,1450.0,0
6,14.39,1.87,2.45,14.6,96.0,2.50,2.52,0.30,1.98,5.25,1.02,3.58,1290.0,0
7,14.06,2.15,2.61,17.6,121.0,2.60,2.51,0.31,1.25,5.05,1.06,3.58,1295.0,0
8,14.83,1.64,2.17,14.0,97.0,2.80,2.98,0.29,1.98,5.20,1.08,2.85,1045.0,0
10,14.10,2.16,2.30,18.0,105.0,2.95,3.32,0.22,2.38,5.75,1.25,3.17,1510.0,0
11,14.12,1.48,2.32,16.8,95.0,2.20,2.43,0.26,1.57,5.00,1.17,2.82,1280.0,0
13,14.75,1.73,2.39,11.4,91.0,3.10,3.69,0.43,2.81,5.40,1.25,2.73,1150.0,0
14,14.38,1.87,2.38,12.0,102.0,3.30,3.64,0.29,2.96,7.50,1.20,3.00,1547.0,0
16,14.30,1.92,2.72,20.0,120.0,2.80,3.14,0.33,1.97,6.20,1.07,2.65,1280.0,0
18,14.19,1.59,2.48,16.5,108.0,3.30,3.93,0.32,1.86,8.70,1.23,2.82,1680.0,0
20,14.06,1.63,2.28,16.0,126.0,3.00,3.17,0.24,2.10,5.65,1.09,3.71,780.0,0
29,14.02,1.68,2.21,16.0,96.0,2.65,2.33,0.26,1.98,4.70,1.04,3.59,1035.0,0
39,14.22,3.99,2.51,13.2,128.0,3.00,3.04,0.20,2.08,5.10,0.89,3.53,760.0,0
45,14.21,4.04,2.44,18.9,111.0,2.85,2.65,0.30,1.25,5.24,0.87,3.33,1080.0,0
46,14.38,3.59,2.28,16.0,102.0,3.25,3.17,0.27,2.19,4.90,1.04,3.44,1065.0,0
48,14.10,2.02,2.40,18.8,103.0,2.75,2.92,0.32,2.38,6.20,1.07,2.75,1060.0,0
56,14.22,1.70,2.30,16.3,118.0,3.20,3.00,0.26,2.03,6.38,0.94,3.31,970.0,0
158,14.34,1.68,2.70,25.0,98.0,2.80,1.31,0.53,2.70,13.00,0.57,1.96,660.0,2
172,14.16,2.51,2.48,20.0,91.0,1.68,0.70,0.44,1.24,9.70,0.62,1.71,660.0,2
177,14.13,4.10,2.74,24.5,96.0,2.05,0.76,0.56,1.35,9.20,0.61,1.60,560.0,2

In [26]:
df.describe()

,alcohol,malic_acid,ash,alcalinity_of_ash,magnesium,total_phenols,flavanoids,nonflavanoid_phenols,proanthocyanins,color_intensity,hue,od280/od315_of_diluted_wines,proline,target
count,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000,178.000000
mean,13.000618,2.336348,2.366517,19.494944,99.741573,2.295112,2.029270,0.361854,1.590899,5.058090,0.957449,2.611685,746.893258,0.938202
std,0.811827,1.117146,0.274344,3.339564,14.282484,0.625851,0.998859,0.124453,0.572359,2.318286,0.228572,0.709990,314.907474,0.775035
min,11.030000,0.740000,1.360000,10.600000,70.000000,0.980000,0.340000,0.130000,0.410000,1.280000,0.480000,1.270000,278.000000,0.000000
25%,12.362500,1.602500,2.210000,17.200000,88.000000,1.742500,1.205000,0.270000,1.250000,3.220000,0.782500,1.937500,500.500000,0.000000
50%,13.050000,1.865000,2.360000,19.500000,98.000000,2.355000,2.135000,0.340000,1.555000,4.690000,0.965000,2.780000,673.500000,1.000000
75%,13.677500,3.082500,2.557500,21.500000,107.000000,2.800000,2.875000,0.437500,1.950000,6.200000,1.120000,3.170000,985.000000,2.000000
max,14.830000,5.800000,3.230000,30.000000,162.000000,3.880000,5.080000,0.660000,3.580000,13.000000,1.710000,4.000000,1680.000000,2.000000

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   alcohol                       178 non-null    float64
 1   malic_acid                    178 non-null    float64
 2   ash                           178 non-null    float64
 3   alcalinity_of_ash             178 non-null    float64
 4   magnesium                     178 non-null    float64
 5   total_phenols                 178 non-null    float64
 6   flavanoids                    178 non-null    float64
 7   nonflavanoid_phenols          178 non-null    float64
 8   proanthocyanins               178 non-null    float64
 9   color_intensity               178 non-null    float64
 10  hue                           178 non-null    float64
 11  od280/od315_of_diluted_wines  178 non-null    float64
 12  proline                       178 non-null    float64
 13  target                        178 non-null    int64
dtypes: float64(13), int64(1)
memory usage: 19.6 KB

In [28]:
print(df.to_string())

     alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity    hue  od280/od315_of_diluted_wines  proline  target
0      14.23        1.71  2.43               15.6      127.0           2.80        3.06                  0.28             2.29         5.640000  1.040                          3.92   1065.0       0
1      13.20        1.78  2.14               11.2      100.0           2.65        2.76                  0.26             1.28         4.380000  1.050                          3.40   1050.0       0
2      13.16        2.36  2.67               18.6      101.0           2.80        3.24                  0.30             2.81         5.680000  1.030                          3.17   1185.0       0
3      14.37        1.95  2.50               16.8      113.0           3.85        3.49                  0.24             2.18         7.800000  0.860                          3.45   1480.0       0
4      13.24        2.59  2.87               21.0      118.0           2.80        2.69                  0.39             1.82         4.320000  1.040                          2.93    735.0       0
5      14.20        1.76  2.45               15.2      112.0           3.27        3.39                  0.34             1.97         6.750000  1.050                          2.85   1450.0       0
6      14.39        1.87  2.45               14.6       96.0           2.50        2.52                  0.30             1.98         5.250000  1.020                          3.58   1290.0       0
7      14.06        2.15  2.61               17.6      121.0           2.60        2.51                  0.31             1.25         5.050000  1.060                          3.58   1295.0       0
8      14.83        1.64  2.17               14.0       97.0           2.80        2.98                  0.29             1.98         5.200000  1.080                          2.85   1045.0       0
9      13.86        1.35  2.27               16.0       98.0           2.98        3.15                  0.22             1.85         7.220000  1.010                          3.55   1045.0       0
10     14.10        2.16  2.30               18.0      105.0           2.95        3.32                  0.22             2.38         5.750000  1.250                          3.17   1510.0       0
11     14.12        1.48  2.32               16.8       95.0           2.20        2.43                  0.26             1.57         5.000000  1.170                          2.82   1280.0       0
12     13.75        1.73  2.41               16.0       89.0           2.60        2.76                  0.29             1.81         5.600000  1.150                          2.90   1320.0       0
13     14.75        1.73  2.39               11.4       91.0           3.10        3.69                  0.43             2.81         5.400000  1.250                          2.73   1150.0       0
14     14.38        1.87  2.38               12.0      102.0           3.30        3.64                  0.29             2.96         7.500000  1.200                          3.00   1547.0       0
15     13.63        1.81  2.70               17.2      112.0           2.85        2.91                  0.30             1.46         7.300000  1.280                          2.88   1310.0       0
16     14.30        1.92  2.72               20.0      120.0           2.80        3.14                  0.33             1.97         6.200000  1.070                          2.65   1280.0       0
17     13.83        1.57  2.62               20.0      115.0           2.95        3.40                  0.40             1.72         6.600000  1.130                          2.57   1130.0       0
18     14.19        1.59  2.48               16.5      108.0           3.30        3.93                  0.32             1.86         8.700000  1.230                          2.82   1680.0       0
19     13.64        3.10  2.56               15.2      116.0           2.70        3.03                  0.17             1.66         5.100000  0.960                          3.36    845.0       0
20     14.06        1.63  2.28               16.0      126.0           3.00        3.17                  0.24             2.10         5.650000  1.090                          3.71    780.0       0
21     12.93        3.80  2.65               18.6      102.0           2.41        2.41                  0.25             1.98         4.500000  1.030                          3.52    770.0       0
22     13.71        1.86  2.36               16.6      101.0           2.61        2.88                  0.27             1.69         3.800000  1.110                          4.00   1035.0       0
23     12.85        1.60  2.52               17.8       95.0           2.48        2.37                  0.26             1.46         3.930000  1.090                          3.63   1015.0       0
24     13.50        1.81  2.61               20.0       96.0           2.53        2.61                  0.28             1.66         3.520000  1.120                          3.82    845.0       0
25     13.05        2.05  3.22               25.0      124.0           2.63        2.68                  0.47             1.92         3.580000  1.130                          3.20    830.0       0
26     13.39        1.77  2.62               16.1       93.0           2.85        2.94                  0.34             1.45         4.800000  0.920                          3.22   1195.0       0
27     13.30        1.72  2.14               17.0       94.0           2.40        2.19                  0.27             1.35         3.950000  1.020                          2.77   1285.0       0
28     13.87        1.90  2.80               19.4      107.0           2.95        2.97                  0.37             1.76         4.500000  1.250                          3.40    915.0       0
29     14.02        1.68  2.21               16.0       96.0           2.65        2.33                  0.26             1.98         4.700000  1.040                          3.59   1035.0       0
30     13.73        1.50  2.70               22.5      101.0           3.00        3.25                  0.29             2.38         5.700000  1.190                          2.71   1285.0       0
31     13.58        1.66  2.36               19.1      106.0           2.86        3.19                  0.22             1.95         6.900000  1.090                          2.88   1515.0       0
32     13.68        1.83  2.36               17.2      104.0           2.42        2.69                  0.42             1.97         3.840000  1.230                          2.87    990.0       0
33     13.76        1.53  2.70               19.5      132.0           2.95        2.74                  0.50             1.35         5.400000  1.250                          3.00   1235.0       0
34     13.51        1.80  2.65               19.0      110.0           2.35        2.53                  0.29             1.54         4.200000  1.100                          2.87   1095.0       0
35     13.48        1.81  2.41               20.5      100.0           2.70        2.98                  0.26             1.86         5.100000  1.040                          3.47    920.0       0
36     13.28        1.64  2.84               15.5      110.0           2.60        2.68                  0.34             1.36         4.600000  1.090                          2.78    880.0       0
37     13.05        1.65  2.55               18.0       98.0           2.45        2.43                  0.29             1.44         4.250000  1.120                          2.51   1105.0       0
38     13.07        1.50  2.10               15.5       98.0           2.40        2.64                  0.28             1.37         3.700000  1.180                          2.69   1020.0       0
39     14.22        3.99  2.51               13.2      128.0           3.00        3.04                  0.20             2.08         5.100000  0.890                          3.53    760.0       0
40     13.56        1.71  2.31               16.2      117.0           3.15        3.29                  0.34             2.34         6.130000  0.950                          3.38    795.0       0
41     13.41        3.84  2.12               18.8       90.0           2.45        2.68                  0.27             1.48         4.280000  0.910                          3.00   1035.0       0
42     13.88        1.89  2.59               15.0      101.0           3.25        3.56                  0.17             1.70         5.430000  0.880                          3.56   1095.0       0
43     13.24        3.98  2.29               17.5      103.0           2.64        2.63                  0.32             1.66         4.360000  0.820                          3.00    680.0       0
44     13.05        1.77  2.10               17.0      107.0           3.00        3.00                  0.28             2.03         5.040000  0.880                          3.35    885.0       0
45     14.21        4.04  2.44               18.9      111.0           2.85        2.65                  0.30             1.25         5.240000  0.870                          3.33   1080.0       0
46     14.38        3.59  2.28               16.0      102.0           3.25        3.17                  0.27             2.19         4.900000  1.040                          3.44   1065.0       0
47     13.90        1.68  2.12               16.0      101.0           3.10        3.39                  0.21             2.14         6.100000  0.910                          3.33    985.0       0
48     14.10        2.02  2.40               18.8      103.0           2.75        2.92                  0.32             2.38         6.200000  1.070                          2.75   1060.0       0
49     13.94        1.73  2.27               17.4      108.0           2.88        3.54                  0.32             2.08         8.900000  1.120                          3.10   1260.0       0
50     13.05        1.73  2.04               12.4       92.0           2.72        3.27                  0.17             2.91         7.200000  1.120                          2.91   1150.0       0
51     13.83        1.65  2.60               17.2       94.0           2.45        2.99                  0.22             2.29         5.600000  1.240                          3.37   1265.0       0
52     13.82        1.75  2.42               14.0      111.0           3.88        3.74                  0.32             1.87         7.050000  1.010                          3.26   1190.0       0
53     13.77        1.90  2.68               17.1      115.0           3.00        2.79                  0.39             1.68         6.300000  1.130                          2.93   1375.0       0
54     13.74        1.67  2.25               16.4      118.0           2.60        2.90                  0.21             1.62         5.850000  0.920                          3.20   1060.0       0
55     13.56        1.73  2.46               20.5      116.0           2.96        2.78                  0.20             2.45         6.250000  0.980                          3.03   1120.0       0
56     14.22        1.70  2.30               16.3      118.0           3.20        3.00                  0.26             2.03         6.380000  0.940                          3.31    970.0       0
57     13.29        1.97  2.68               16.8      102.0           3.00        3.23                  0.31             1.66         6.000000  1.070                          2.84   1270.0       0
58     13.72        1.43  2.50               16.7      108.0           3.40        3.67                  0.19             2.04         6.800000  0.890                          2.87   1285.0       0
59     12.37        0.94  1.36               10.6       88.0           1.98        0.57                  0.28             0.42         1.950000  1.050                          1.82    520.0       1
60     12.33        1.10  2.28               16.0      101.0           2.05        1.09                  0.63             0.41         3.270000  1.250                          1.67    680.0       1
61     12.64        1.36  2.02               16.8      100.0           2.02        1.41                  0.53             0.62         5.750000  0.980                          1.59    450.0       1
62     13.67        1.25  1.92               18.0       94.0           2.10        1.79                  0.32             0.73         3.800000  1.230                          2.46    630.0       1
63     12.37        1.13  2.16               19.0       87.0           3.50        3.10                  0.19             1.87         4.450000  1.220                          2.87    420.0       1
64     12.17        1.45  2.53               19.0      104.0           1.89        1.75                  0.45             1.03         2.950000  1.450                          2.23    355.0       1
65     12.37        1.21  2.56               18.1       98.0           2.42        2.65                  0.37             2.08         4.600000  1.190                          2.30    678.0       1
66     13.11        1.01  1.70               15.0       78.0           2.98        3.18                  0.26             2.28         5.300000  1.120                          3.18    502.0       1
67     12.37        1.17  1.92               19.6       78.0           2.11        2.00                  0.27             1.04         4.680000  1.120                          3.48    510.0       1
68     13.34        0.94  2.36               17.0      110.0           2.53        1.30                  0.55             0.42         3.170000  1.020                          1.93    750.0       1
69     12.21        1.19  1.75               16.8      151.0           1.85        1.28                  0.14             2.50         2.850000  1.280                          3.07    718.0       1
70     12.29        1.61  2.21               20.4      103.0           1.10        1.02                  0.37             1.46         3.050000  0.906                          1.82    870.0       1
71     13.86        1.51  2.67               25.0       86.0           2.95        2.86                  0.21             1.87         3.380000  1.360                          3.16    410.0       1
72     13.49        1.66  2.24               24.0       87.0           1.88        1.84                  0.27             1.03         3.740000  0.980                          2.78    472.0       1
73     12.99        1.67  2.60               30.0      139.0           3.30        2.89                  0.21             1.96         3.350000  1.310                          3.50    985.0       1
74     11.96        1.09  2.30               21.0      101.0           3.38        2.14                  0.13             1.65         3.210000  0.990                          3.13    886.0       1
75     11.66        1.88  1.92               16.0       97.0           1.61        1.57                  0.34             1.15         3.800000  1.230                          2.14    428.0       1
76     13.03        0.90  1.71               16.0       86.0           1.95        2.03                  0.24             1.46         4.600000  1.190                          2.48    392.0       1
77     11.84        2.89  2.23               18.0      112.0           1.72        1.32                  0.43             0.95         2.650000  0.960                          2.52    500.0       1
78     12.33        0.99  1.95               14.8      136.0           1.90        1.85                  0.35             2.76         3.400000  1.060                          2.31    750.0       1
79     12.70        3.87  2.40               23.0      101.0           2.83        2.55                  0.43             1.95         2.570000  1.190                          3.13    463.0       1
80     12.00        0.92  2.00               19.0       86.0           2.42        2.26                  0.30             1.43         2.500000  1.380                          3.12    278.0       1
81     12.72        1.81  2.20               18.8       86.0           2.20        2.53                  0.26             1.77         3.900000  1.160                          3.14    714.0       1
82     12.08        1.13  2.51               24.0       78.0           2.00        1.58                  0.40             1.40         2.200000  1.310                          2.72    630.0       1
83     13.05        3.86  2.32               22.5       85.0           1.65        1.59                  0.61             1.62         4.800000  0.840                          2.01    515.0       1
84     11.84        0.89  2.58               18.0       94.0           2.20        2.21                  0.22             2.35         3.050000  0.790                          3.08    520.0       1
85     12.67        0.98  2.24               18.0       99.0           2.20        1.94                  0.30             1.46         2.620000  1.230                          3.16    450.0       1
86     12.16        1.61  2.31               22.8       90.0           1.78        1.69                  0.43             1.56         2.450000  1.330                          2.26    495.0       1
87     11.65        1.67  2.62               26.0       88.0           1.92        1.61                  0.40             1.34         2.600000  1.360                          3.21    562.0       1
88     11.64        2.06  2.46               21.6       84.0           1.95        1.69                  0.48             1.35         2.800000  1.000                          2.75    680.0       1
89     12.08        1.33  2.30               23.6       70.0           2.20        1.59                  0.42             1.38         1.740000  1.070                          3.21    625.0       1
90     12.08        1.83  2.32               18.5       81.0           1.60        1.50                  0.52             1.64         2.400000  1.080                          2.27    480.0       1
91     12.00        1.51  2.42               22.0       86.0           1.45        1.25                  0.50             1.63         3.600000  1.050                          2.65    450.0       1
92     12.69        1.53  2.26               20.7       80.0           1.38        1.46                  0.58             1.62         3.050000  0.960                          2.06    495.0       1
93     12.29        2.83  2.22               18.0       88.0           2.45        2.25                  0.25             1.99         2.150000  1.150                          3.30    290.0       1
94     11.62        1.99  2.28               18.0       98.0           3.02        2.26                  0.17             1.35         3.250000  1.160                          2.96    345.0       1
95     12.47        1.52  2.20               19.0      162.0           2.50        2.27                  0.32             3.28         2.600000  1.160                          2.63    937.0       1
96     11.81        2.12  2.74               21.5      134.0           1.60        0.99                  0.14             1.56         2.500000  0.950                          2.26    625.0       1
97     12.29        1.41  1.98               16.0       85.0           2.55        2.50                  0.29             1.77         2.900000  1.230                          2.74    428.0       1
98     12.37        1.07  2.10               18.5       88.0           3.52        3.75                  0.24             1.95         4.500000  1.040                          2.77    660.0       1
99     12.29        3.17  2.21               18.0       88.0           2.85        2.99                  0.45             2.81         2.300000  1.420                          2.83    406.0       1

In [29]:
def highlight_max(s):
    is_max = s == s.max()
    return ['background-color: yellow' if v else '' for v in is_max]

styled_df = df.style.apply(highlight_max)
styled_df